filetype off
call pathogen#infect()
call pathogen#helptags()
set number
set noswapfile
set mouse=a

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Show the mode you are on the last line.
set showmode

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

packadd! dracula
syntax enable
colorscheme dracula

filetype plugin indent on
syntax on

map <F5> :NERDTreeToggle<CR>
